Add LICENSE
rancher/hosted-providers-e2e pull request #5
Opened 2023-12-12 06:05 UTC by valaparthvi

2023-12-14 09:47 UTC, cpinjani requested changes
lgtm, can we add copyright similar to https://github.com/rancher/elemental/blob/main/tests/e2e/configure_test.go#L2

2023-12-26 07:53 UTC, valaparthvi commented
> lgtm, can we add copyright similar to https://github.com/rancher/elemental/blob/main/tests/e2e/configure_test.go#L2

@juadk @ldevulder why did you feel the need to add license to every test file? Also do you copy paste the license every time you create a new file or do you have a boiler plate for it?

2024-02-05 05:26 UTC, cpinjani commented on hosted/aks/p0/p0_importing_test.go
> +Copyright © 2022 - 2024 SUSE LLC
```suggestion
Copyright © 2023 - 2024 SUSE LLC
```

2024-02-05 09:29 UTC, cpinjani approved these changes

2024-02-05 14:42 UTC, merged